device: 'cuda'
seed: 42
output_path: "/home/cvlab04/project/jinhyeok/dmt-personal/diffusion-motion-transfer/result/step-10-layer-all"
data_path: "/home/cvlab04/project/jinhyeok/dmt-personal/diffusion-motion-transfer/landscape/frames"
latents_path: "/home/cvlab04/project/jinhyeok/dmt-personal/diffusion-motion-transfer/landscape/latents"
source_prompt: "Amazing quality, masterpiece, snow-covered mountains and forests are zoomed in"
target_prompt: "Amazing quality, masterpiece, A yellow school bus pulling into a driveway"
negative_prompt: "bad quality, distortions, unrealistic, distorted image, watermark, signature"
guidance_scale: 10

# swapping attentions
load_swapping_attn: True
swapping_load_path: "/media/data1/dmt/swapping_attns_zoomin"
swapping_step: 45

with_lr_decay: True
optim_lr: 0.01
scale_range: [0.007 , 0.004]
optimization_steps: 10


max_frames: 12
n_timesteps: 50
max_guidance_timestep: 1
min_guidance_timestep: 0.6
features_loss_weight: 0
global_averaging: True
features_diff_loss_weight: 1

restart_sampling: False
random_init: True
high_freq_replacement_init: False
downsample_factor: 4

use_upsampler_features: True
use_temporal_attention_features: True
use_spatial_attention_features: True
use_conv_features: True
use_temp_conv_features: True
up_res_dict: {1: [1]}
guidance_before_res: True
