video_path: /home/cvlab04/project/jinhyeok/diffusion-motion-transfer/AIST/frames_crop/AIST_group_1
save_dir: /home/cvlab04/project/jinhyeok/diffusion-motion-transfer/AIST/latents
max_number_of_frames: 12

n_timesteps: 999
prompt: "Amazing quality, masterpiece, three men are dancing in the room"
negative_prompt: ""
save_ddim_reconstruction: False