video_path: /home/cvlab04/project/jinhyeok/dmt-personal/diffusion-motion-transfer/landscape/frames
save_dir: /home/cvlab04/project/jinhyeok/dmt-personal/diffusion-motion-transfer/landscape/latents
max_number_of_frames: 12

n_timesteps: 999
prompt: "Amazing quality, masterpiece, snow-covered mountains and forests are zoomed in"
negative_prompt: ""
save_ddim_reconstruction: False

# swapping attentions
save_swapping_attn: True
swapping_save_path: "/media/data1/dmt/swapping_attns_zoomin"